version: "3"

services:
  database:
    restart: always
    image: postgres:latest
    container_name: postgres-latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
